import subprocess
import os
import re
from collections import defaultdict
import math
import argparse
import sys

def parse_polynomial(eq_str):
    eq_str = eq_str.replace(" ", "")

    # Trap missing carets (e.g., 'x2' instead of 'x^2')
    if re.search(r'[a-zA-Z]\d', eq_str):
        raise ValueError("Improper syntax: Use '^' for exponents (e.g., 'x^2' instead of 'x2').")

    if "=" in eq_str:
        left_str, right_str = eq_str.split("=", 1)
    else:
        left_str, right_str = eq_str, "0"

    # Pattern: (Coefficient)(Variable)^(Exponent)
    pattern = r"([+-]?\d*\.?\d*)([a-zA-Z]?)(?:\^(\d+))?"

    merged_terms = defaultdict(float)
    detected_var = None

    def extract_terms(side_str, multiplier):
        nonlocal detected_var
        for match in re.finditer(pattern, side_str):
            coef_str, var_str, exp_str = match.groups()

            if not coef_str and not var_str:
                continue

            if coef_str in ("", "+"):
                coef = 1.0
            elif coef_str == "-":
                coef = -1.0
            else:
                coef = float(coef_str)
            coef *= multiplier

            if var_str:
                if var_str.lower() in ('i', 'e'):
                    raise ValueError(f"Variable '{var_str}' is reserved for math constants.")
                if detected_var and var_str != detected_var:
                    raise ValueError("Multiple variables detected. Please use only one.")
                detected_var = var_str

            if var_str:
                exp = int(exp_str) if exp_str else 1
            else:
                exp = 0

            merged_terms[exp] += coef

    extract_terms(left_str, 1)
    extract_terms(right_str, -1)

    return dict(merged_terms), detected_var


def build_dense_array(merged_terms):
    # 1. Purge all zero coefficients to cull cancelled leading degrees
    # Using a small epsilon handles standard floating-point subtraction artifacts
    cleaned_terms = {exp: coef for exp, coef in merged_terms.items() if abs(coef) > 1e-15}

    # 2. Trap edge cases where everything cancels out
    if not cleaned_terms:
        return []

    # 3. Find the true maximum degree
    max_degree = max(cleaned_terms.keys())
    return [cleaned_terms.get(i, 0.0) for i in range(max_degree, -1, -1)]


def generate_dk_guesses(dense_array):
    '''
    Generate complex guess for the Durand-Kerner algorithm for solving roots of polynomials
    '''
    degree = len(dense_array) - 1
    if degree < 1:
        return []

    # 1. Normalize coefficients so the leading term is 1.0
    # Cast strings back to floats strictly for the initial radius geometry
    lead_coef = float(dense_array[0])
    norm_coefs = [float(c) / lead_coef for c in dense_array]

    # 2. Calculate Cauchy's bound to size the initial circle
    max_coef = max(abs(c) for c in norm_coefs[1:])
    radius = 1.0 + max_coef

    guesses = []
    # Arbitrary offset angle to prevent perfect axial symmetry
    offset = 0.75

    # 3. Distribute guesses around the complex plane
    for k in range(degree):
        angle = (2 * math.pi * k / degree) + offset
        real_part = radius * math.cos(angle)
        imag_part = radius * math.sin(angle)

        # Format the guess into a hugecalc-compatible complex string WITHOUT spaces
        sign = "+" if imag_part >= 0 else "-"
        guesses.append(f"{real_part}{sign}{abs(imag_part)}i")

    return guesses


def dk_solve(equation_template, initial_guesses, hctol):
    '''
    Executes the Durand-Kerner algorithm to find all complex roots of a polynomial simultaneously.

    This function relies exclusively on the hugecalc.py engine for all arithmetic via hc_eval().
    It iteratively updates an array of complex string guesses until the rounded values
    stabilize at the requested tolerance level.

    Args:
        equation_template (str): The formatted polynomial string (e.g., "1.000 * {x} ^ 2 + -9.000").
        initial_guesses (list): A list of complex number strings generated by generate_dk_guesses().
        hctol (int): The target decimal precision for convergence.

    Returns:
        list: A list of string representations of the finalized roots.
    '''
    degree = len(initial_guesses)
    current_guesses = list(initial_guesses)

    # Scale iterations based on requested precision to prevent infinite loops
    working_tol = hctol + 5
    max_iterations = int(working_tol * 4.0) + 20

    print(f"Durand-Kerner Hunting for {degree} roots (Targeting {hctol} digits)...")

    for iteration in range(max_iterations):
        next_guesses = []

        # Update each root guess individually
        for k in range(degree):
            x_k = current_guesses[k]

            # 1. Evaluate Numerator: P(x_k) and scrub spaces
            p_val = hc_eval(equation_template.format(x=x_k)).replace(" ", "")

            # 2. Evaluate Denominator: Product of (x_k - x_j) for all j != k
            denom = "1"
            for j in range(degree):
                if j == k:
                    continue
                x_j = current_guesses[j]

                # Subtract the other guess from the current guess
                diff = hc_eval(f"{x_k} - {x_j}").replace(" ", "")

                # Multiply it into the running denominator product
                denom = hc_eval(f"{denom} * {diff}").replace(" ", "")

            # 3. Calculate the step size: P(x_k) / denominator
            step = hc_eval(f"{p_val} / {denom}").replace(" ", "")

            # 4. Calculate the new guess: x_k - step
            new_x_k = hc_eval(f"{x_k} - {step}").replace(" ", "")
            next_guesses.append(new_x_k)

        # 5. Convergence Check
        # Round both the old and new arrays to the target tolerance to check for stability
        all_stable = True
        for k in range(degree):
            old_rounded = hc_eval(f"{current_guesses[k]} round {hctol}")
            new_rounded = hc_eval(f"{next_guesses[k]} round {hctol}")

            if old_rounded != new_rounded:
                all_stable = False
                break

        current_guesses = next_guesses

        print(f"Iter {iteration+1:02d} | Roots updated. Checking stability...")

        if all_stable:
            print(f"\nTolerance reached! All {degree} roots stabilized at {hctol} digits.")
            # Format the final output cleanly
            return [format_dec(hc_eval(f"{root} round {hctol}")) for root in current_guesses]

    print(f"\nWARNING: Maximum iterations ({max_iterations}) reached without stable tolerance.")
    return [format_dec(hc_eval(f"{root} round {hctol}")) for root in current_guesses]


def build_equation_template(dense_array):
    '''
    Converts a dense coefficient array into a chained hugecalc pipe string
    using Horner's Method to guarantee strict execution order.
    '''
    if not dense_array:
        return "0 + 0"

    # If it's just a constant (degree 0), pad it with a dummy operation
    # so hugecalc has a valid expression to evaluate
    if len(dense_array) == 1:
        return f"{dense_array[0]} + 0"

    # Seed the first full operation (op1 op op2)
    template = f"{dense_array[0]} * {{x}} | + {dense_array[1]}"

    # Chain the remaining coefficients, separating every * and + with a pipe
    for coef in dense_array[2:]:
        template += f" | * {{x}} | + {coef}"

    return template


def hc_eval(command_string):
    """Fires a command to hugecalc, natively supporting chained pipe '|' operations."""
    stages = [stage.strip() for stage in command_string.split('|')]

    current_input = None
    for stage in stages:
        cmd = ['python', 'hugecalc.py'] + stage.split()

        if current_input:
            # Feed the previous output into the stdin of the current hugecalc stage
            result = subprocess.run(cmd, input=current_input, capture_output=True, text=True)
        else:
            result = subprocess.run(cmd, capture_output=True, text=True)

        if not result.stdout.strip():
            raise ValueError(f"hugecalc failed at '{stage}': {result.stderr}")

        current_input = result.stdout.strip()

    return current_input


def format_dec(raw_str):
    """Converts raw piped output (e.g., '+25e-1') to a readable decimal string."""
    if 'e' not in raw_str:
        return raw_str

    sign = '-' if raw_str.startswith('-') else ''
    core = raw_str.lstrip('+-')
    mantissa, exp_str = core.split('e')
    exp = int(exp_str)

    if exp >= 0:
        return sign + mantissa + ('0' * exp)

    dec_places = abs(exp)
    if len(mantissa) <= dec_places:
        mantissa = mantissa.zfill(dec_places + 1)

    insert_pos = len(mantissa) - dec_places
    res = mantissa[:insert_pos] + '.' + mantissa[insert_pos:]

    # Clean up trailing decimal zeros
    if '.' in res:
        res = res.rstrip('0').rstrip('.')
    return sign + (res or '0')


def format_error(raw_str):
    """Formats errors cleanly, switching to SCI if sig-figs are pushed past 35 chars."""
    if raw_str in ('0', '+0e0', '-0e0'):
        return '0'

    dec_str = format_dec(raw_str)
    truncated = dec_str[:35]

    # Check if the visible portion is entirely zeros (e.g., "0.0000000...")
    # If the truncated part is empty of non-zero digits, our data fell off the screen.
    if not truncated.lstrip('-').replace('.', '').strip('0'):
        sign = '-' if raw_str.startswith('-') else ''
        core = raw_str.lstrip('+-')

        if 'e' in core:
            mantissa, exp_str = core.split('e')
            sci_exp = int(exp_str) + len(mantissa) - 1
            sci_mantissa = mantissa[0] + '.' + mantissa[1:] if len(mantissa) > 1 else mantissa
            return f"{sign}{sci_mantissa}e{sci_exp}"

    return dec_str


def bisect_solve(equation_template, target, low_str, high_str, hctol):
    working_tol = hctol + 5
    clean_eq = equation_template.replace('{x}', 'x')
    print(f"Hunting for {clean_eq} = {target} (Targeting {hctol} digits)...")

    # Evaluate boundaries to determine function direction
    y_low = hc_eval(equation_template.format(x=low_str))
    y_high = hc_eval(equation_template.format(x=high_str))

    direction_check = hc_eval(f"{y_high} - {y_low}")
    is_increasing = not direction_check.startswith('-')

    iterations = int(working_tol * 3.4) + 10
    last_rounded = ""
    stable_count = 0

    for i in range(iterations):
        sum_val = hc_eval(f"{low_str} + {high_str}")
        mid_str = hc_eval(f"{sum_val} / 2")

        guess_res = hc_eval(equation_template.format(x=mid_str))
        error_diff = hc_eval(f"{guess_res} - {target}")

        current_rounded = hc_eval(f"{mid_str} round {hctol}")

        disp_x = format_dec(mid_str)
        disp_err = format_error(error_diff)
        print(f"Iter {i+1:02d} | x = {disp_x[:35]:<35} | Error = {disp_err[:35]}")

        if error_diff in ('0', '+0e0', '-0e0'):
            print("\nExact absolute convergence reached!")
            return format_dec(current_rounded)

        if current_rounded == last_rounded:
            stable_count += 1
            if stable_count >= 2:
                print(f"\nTolerance reached! Result stabilized at {hctol} digits.")
                return format_dec(current_rounded)
        else:
            stable_count = 0
            last_rounded = current_rounded

        if error_diff.startswith('-'):
            if is_increasing: low_str = mid_str
            else: high_str = mid_str
        else:
            if is_increasing: high_str = mid_str
            else: low_str = mid_str

    print(f"\nWARNING: Maximum iterations ({iterations}) reached without reaching stable tolerance.")
    return format_dec(current_rounded)


def newton_solve(equation_template, deriv_template, target, guess_str, hctol):
    clean_eq = equation_template.replace('{x}', 'x')
    print(f"Newton Hunting for {clean_eq} = {target} (Targeting {hctol} digits)...")

    working_tol = hctol + 5
    iterations = int(working_tol * 3.4) + 10
    last_rounded = ""
    stable_count = 0
    current_x = guess_str

    for i in range(iterations):
        f_val = hc_eval(equation_template.format(x=current_x))
        f_prime = hc_eval(deriv_template.format(x=current_x))

        error_val = hc_eval(f"{f_val} - {target}")
        step_val = hc_eval(f"{error_val} / {f_prime}")
        current_x = hc_eval(f"{current_x} - {step_val}")

        current_rounded = hc_eval(f"{current_x} round {hctol}")

        disp_x = format_dec(current_x)
        disp_err = format_error(error_val)
        print(f"Iter {i+1:02d} | x = {disp_x[:35]:<35} | Error = {disp_err[:35]}")

        if error_val in ('0', '+0e0', '-0e0'):
            print("\nExact absolute convergence reached!")
            return format_dec(current_rounded)

        if current_rounded == last_rounded:
            stable_count += 1
            if stable_count >= 2:
                print(f"\nTolerance reached! Result stabilized at {hctol} digits.")
                return format_dec(current_rounded)
        else:
            stable_count = 0
            last_rounded = current_rounded

    print(f"\nWARNING: Maximum iterations ({iterations}) reached without stable tolerance.")
    return format_dec(current_rounded)


def main():
    parser = argparse.ArgumentParser(description="HugeCalc Equation Solver (hcsolver)")
    parser.add_argument("equation", type=str, help="The equation string (e.g., 'x^2 - x - 6 = 0')")
    parser.add_argument("--tol", type=int, default=int(os.environ.get('HCTOL', 25)),
                        help="Target decimal precision (defaults to HCTOL env var or 25)")

    args = parser.parse_args()

    # FORCE the environment variable so all hugecalc subprocesses inherit it natively
    os.environ['HCTOL'] = str(args.tol)

    eq_input = args.equation.lower()

    print(f"\n--- HugeCalc Solver ---")
    print(f"Input: {args.equation}")
    print(f"Precision Target: {args.tol} digits\n")

    # 1. Transcendental Routing Trap
    # If the equation contains trig or log functions, it requires Newton/Bisection
    transcendental_sigs = ['sin', 'cos', 'tan', 'ln', 'log']
    if any(sig in eq_input for sig in transcendental_sigs):
        print("Error: Transcendental routing (Newton/Bisection) via CLI is not yet implemented.")
        print("Please input a polynomial equation.")
        sys.exit(1)

    # 2. Polynomial Routing
    try:
        merged_dict, var_name = parse_polynomial(args.equation)
        dense_arr = build_dense_array(merged_dict)

        if not dense_arr:
            print("Error: Equation simplified to zero or is invalid.")
            sys.exit(1)

        eq_template = build_equation_template(dense_arr)
        guesses = generate_dk_guesses(dense_arr)

        final_roots = dk_solve(eq_template, guesses, args.tol)

        print("\nFinal Solved Roots:")
        for i, root in enumerate(final_roots):
            print(f"Root {i+1}: {root}")

    except Exception as e:
        print(f"\nSolver failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
